version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - claim-network

networks:
  claim-network:
    driver: bridge

volumes:
  sqldata: 